CREATE TABLE Authentication (
  authNo INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  authCode INT(6)
  );

CREATE TABLE Bookmark (
  userID INT(10) NOT NULL,
  postID INT(10) NOT NULL
  );

CREATE TABLE Comment (
  commentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  description MEDIUMTEXT NOT NULL,
  commPhoto TEXT,
  commentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  postID INT(10) NOT NULL,
  userID INT(10) 
  );

CREATE TABLE Feedback (
  feedbackID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  description MEDIUMTEXT NOT NULL,
  feedbackPhoto TEXT,
  feedbackDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userID INT(10)
  );

CREATE TABLE Post (
  postID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  description MEDIUMTEXT NOT NULL,
  postPhoto TEXT,
  postDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userID INT(10)
  );

CREATE TABLE Report (
  reportID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reportDesc VARCHAR(50) NOT NULL,
  reportType VARCHAR(8) NOT NULL,
  reportNo INT(10) NOT NULL,
  reportDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userID INT(10) NOT NULL,
  status VARCHAR(10) NOT NULL
  );

CREATE TABLE Upvote (
  userID INT(10) NOT NULL,
  contentType VARCHAR(8) NOT NULL,
  contentNo INT(10) NOT NULL
  );

CREATE TABLE User (
  userID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  userPhoto TEXT,
  bio TINYTEXT,
  gender VARCHAR(10) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password TEXT NOT NULL,
  regDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  role VARCHAR(5) NOT NULL DEFAULT 'User',
  status VARCHAR(6) NOT NULL DEFAULT 'Active'
  );